### ISSUE TITLE
Code Feedback

### ISSUE THREAD

**Issue by StefanGerrits2** [TomasS666/web-app-from-scratch-1920#2]
## Code Feedback

* Sometimes I see extra white lines (enters) between code, try to keep this consistent.
* I like the way of multiple functions calling eachother to create the template, I see no global variables which is good.
* I see good error handling
* I'd suggest creating modules for these different functions, for example the `genre` function. That one creates the template which deserves it's own module in my opinion.
* Add more comments to your code, this makes it easier to read for yourself and others aswell.

**Comment by TomasStolp** [comment]
Thanks buddy! This issue is resolved.
