### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by StefanGerrits2** [TomasS666/web-app-from-scratch-1920#21]
Live demo ziet er al goed uit!

Je zou een filter kunnen maken voor de verschillende genres van de films.

Ook zou je op de detail page misschien vergelijkbare films (bijvoorbeeld van hetzelfde genre) kunnen tonen. Daarnaast wat extra informatie over de film tonen kan geen kwaad :)

Op je detail pagina zou je ook nog een "Terug" knop kunnen toevoegen, dit zou je kunnen doen met een link met als `href=""`, het enige nadeel is dat hij dan waarschijnlijk weer fetched. Dit kan een tijdelijke oplossing zijn.

Om dit opnieuw fetchen op te lossen kan je local storage gebruiken.

**Comment by TomasStolp** [comment]
Thanks man, ik ben een wat andere weg ingeslagen uiteindelijk. Vette features noem je daar. Ik had er veel meer uit kunnen halen, maar ik moet concessies maken. Maar ik ga zeker door met dit project om het beter en rijker te maken.
