### ISSUE TITLE
Change cleanDom to a replace function

### ISSUE THREAD

**Issue by GiovanniKaaijk** [TomasS666/web-app-from-scratch-1920#23]
Right now you are deleting all the childs within an element, then you are rendering content to that same element. You could change this to a function that replaces the element with a new element.
https://github.com/TomasS666/web-app-from-scratch-1920/blob/534367de8948bd7de7c26672c392e96b833f2c02/src/js/app.js#L57-L58

For example:
```js
function replaceNode (newNode, domTarget) => {
    domTarget.replaceWith(newNode);
    return newNode;
  };
```

**Comment by TomasStolp** [comment]
That would be a nice pattern. But coming back to it, I'd have to change a lot of other depending functionality. I'm definitely looking into it next week.
