### ISSUE TITLE
Functie benaming

### ISSUE THREAD

**Issue by cenikk** [TomasS666/web-app-from-scratch-1920#4]
De benaming van je functie op lijn 55 is momenteel 'genre', maar als ik het goed begrijp vraag je vervolgens nergens in de functie op naar de genre van de films en pak je een algemeen lijst. Dit was voor mij best verwarrend omdat ik dacht dat deze functie dient voor een algemeen genre lijst van films.

https://github.com/TomasS666/web-app-from-scratch-1920/blob/69d49b221342aaf7a50e23a85d1d586a8e7743e2/docs/js/app.js#L55

**Comment by TomasStolp** [comment]
Ja, ik vraag wel een genre op. Ik pak 2 genres, maar de genres bestaan uit een id. 

Misschien is het netter als ik nog een soort van mapping maak zodat ik genre termen in kan voeren die ze omzet naar de juiste genre id.

En het is ook nog niet dynamisch.

Thanks! Ik ga er verder naar kijken.
